version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lmnp
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3366:3306'
    environment:
      - MYSQL_DATABASE=lmnp_db
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8080:80"