# Generated by Django 4.1 on 2022-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facture', models.CharField(blank=True, max_length=255)),
                ('date_facturation', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Montant HT')),
                ('amount_ttc', models.FloatField(blank=True, null=True, verbose_name='Montant TTC')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('facture_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'facture',
            },
        ),
    ]
